### ISSUE TITLE
tag?

### ISSUE THREAD

**Issue by mhekkel** [elsid/newuoa-c#1]
For a couple of my projects I depend on this library and I'm grateful you ported this library to C++.

But now I'm moving many of my projects into Debian and I would like to include this library there as well. For this to work best, it would be nice to have a tag on this repository, preferably something like v1.0.0

Could you please tag this repository?

regards, -maarten

**Comment by elsid** [comment]
This is reasonable, so I added a tag and a release with a summary of my changes.
